// @ts-nocheck
// Service Worker entry for TrafficWatch AI PWA
// Handles: precaching, runtime caching, push notifications, offline fallback, update detection

import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from "workbox-strategies";

// ─── Cache Versioning ─────────────────────────────────
// Bump this version to invalidate all runtime caches
const CACHE_VERSION = "v3";
const CACHE_NAMES = {
  googleFonts: `google-fonts-${CACHE_VERSION}`,
  mapTiles: `map-tiles-${CACHE_VERSION}`,
  api: `api-${CACHE_VERSION}`,
  images: `images-${CACHE_VERSION}`,
  static: `static-${CACHE_VERSION}`,
};

// Clean up old precaches
cleanupOutdatedCaches();

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// ─── Runtime Caching ───────────────────────────────────

// Cache Google Fonts with Cache First strategy (long-lived)
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: CACHE_NAMES.googleFonts,
  })
);

// Cache Leaflet tile images with Cache First (long TTL — 30 days)
registerRoute(
  /^https:\/\/[acst]\.tile\.openstreetmap\.org\/.*/i,
  new CacheFirst({
    cacheName: CACHE_NAMES.mapTiles,
    plugins: [
      {
        cacheWillUpdate: async ({ response }) => {
          if (response && response.status === 200) return response;
          return null;
        },
      },
    ],
  })
);

// Cache API responses with Network First (short TTL — 15 min)
registerRoute(
  /^https:\/\/.*\.supabase\.co\/.*/i,
  new NetworkFirst({
    cacheName: CACHE_NAMES.api,
    networkTimeoutSeconds: 5,
    plugins: [
      {
        cacheWillUpdate: async ({ response }) => {
          if (response && response.status === 200) {
            // Don't cache non-GET or mutation endpoints
            return response;
          }
          return null;
        },
      },
    ],
  })
);

// Cache static images with Cache First (7 days)
registerRoute(
  /\.(?:png|jpg|jpeg|svg|gif|webp|avif)$/,
  new CacheFirst({
    cacheName: CACHE_NAMES.images,
  })
);

// Cache JS and CSS with StaleWhileRevalidate (instant load, updates in background)
registerRoute(
  /\.(?:js|css|mjs)$/,
  new StaleWhileRevalidate({
    cacheName: CACHE_NAMES.static,
  })
);

// ─── Push Notification Event Handling ──────────────────

/**
 * Handle incoming push events from the server.
 * The server sends a JSON payload with title, body, icon, and data.
 */
self.addEventListener("push", (event) => {
  if (!(self.Notification && self.Notification.permission === "granted")) {
    return;
  }

  let data = {
    title: "TrafficWatch AI",
    body: "New notification",
    icon: "/icons/icon-192x192.png",
    badge: "/icons/icon-96x96.png",
    tag: `tw-${Date.now()}`,
    vibrate: [100],
    requireInteraction: false,
    silent: false,
    data: {
      url: "/dashboard",
      timestamp: new Date().toISOString(),
    },
  };

  try {
    if (event.data) {
      const payload = event.data.json();
      data = { ...data, ...payload };
    }
  } catch {
    // Plain text fallback
    if (event.data) {
      data.body = event.data.text();
    }
  }

  // Vibrate pattern based on urgency
  if (data.requireInteraction || data.data?.priority === "urgent") {
    data.vibrate = [200, 100, 200, 100, 200];
  }

  event.waitUntil(
    self.registration.showNotification(data.title, {
      body: data.body,
      icon: data.icon || "/icons/icon-192x192.png",
      badge: data.badge || "/icons/icon-96x96.png",
      tag: data.tag || `tw-${Date.now()}`,
      vibrate: data.vibrate,
      requireInteraction: data.requireInteraction ?? false,
      silent: data.silent ?? false,
      data: data.data || {},
      actions: [
        {
          action: "open",
          title: "Open",
        },
        {
          action: "dismiss",
          title: "Dismiss",
        },
      ],
    })
  );
});

/**
 * Handle notification click events.
 * - Clicking the notification body opens the app to the target URL.
 * - Clicking an action button performs the corresponding action.
 */
self.addEventListener("notificationclick", (event) => {
  event.notification.close();

  const urlToOpen = event.notification.data?.url || "/dashboard";

  if (event.action === "dismiss") {
    // Just close the notification
    return;
  }

  // Open or focus the app window
  event.waitUntil(
    clients.matchAll({ type: "window", includeUncontrolled: true }).then((windowClients) => {
      // Check if there's already a window open
      for (const client of windowClients) {
        if (client.url.includes(self.location.origin) && "focus" in client) {
          // Navigate to the target URL
          client.navigate(urlToOpen);
          return client.focus();
        }
      }
      // Open a new window
      if (clients.openWindow) {
        return clients.openWindow(urlToOpen);
      }
    })
  );
});

// ─── Offline Fallback ──────────────────────────────────

/**
 * Handle navigation requests — serve cached offline page when offline.
 */
self.addEventListener("fetch", (event) => {
  if (event.request.mode === "navigate") {
    event.respondWith(
      fetch(event.request).catch(() => {
        return caches.match("/offline-fallback.html").then((response) => {
          if (response) return response;
          // Last resort: return a minimal offline page
          return new Response(
            "<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Offline - TrafficWatch AI</title><style>body{font-family:sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;background:#0f172a;color:#e2e8f0;text-align:center;padding:20px}div{max-width:400px}.shield{font-size:48px;margin-bottom:16px}h1{font-size:20px;margin:0 0 8px}p{color:#94a3b8;font-size:14px;line-height:1.5}</style></head><body><div><div class='shield'>🛡️</div><h1>You're Offline</h1><p>TrafficWatch AI is unavailable offline. Please check your connection and try again.</p></div></body></html>",
            { headers: { "Content-Type": "text/html;charset=UTF-8" } }
          );
        });
      })
    );
  }
});

// ─── Service Worker Lifecycle ──────────────────────────

/**
 * Handle messages from the client:
 * - SKIP_WAITING: activate the new SW immediately
 * - SHOW_NOTIFICATION: display a notification from client code
 */
self.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") {
    self.skipWaiting();
  }

  // Handle notification data from client
  if (event.data?.type === "SHOW_NOTIFICATION") {
    const { title, options } = event.data;
    event.waitUntil(
      self.registration.showNotification(title, options)
    );
  }
});

/**
 * Clean up old caches on activation.
 * - Removes caches outside the current versioned whitelist.
 * - Claims all open clients so the new SW controls them.
 */
self.addEventListener("activate", (event) => {
  const cacheWhitelist = Object.values(CACHE_NAMES);

  event.waitUntil(
    (async () => {
      // Delete old/unversioned caches
      const cacheNames = await caches.keys();
      await Promise.all(
        cacheNames.map((name) => {
          if (!cacheWhitelist.includes(name)) {
            // Also remove old workbox-precaching caches
            if (name.startsWith("workbox-precaching-")) {
              return caches.delete(name);
            }
            // Remove unversioned caches from previous versions
            return caches.delete(name);
          }
        })
      );

      // Claim all clients immediately
      await clients.claim();

      // Notify all clients about the update
      const allClients = await clients.matchAll({ includeUncontrolled: true });
      allClients.forEach((client) => {
        client.postMessage({ type: "SW_ACTIVATED", cacheVersion: CACHE_VERSION });
      });
    })()
  );
});
