// @ts-nocheck
// Service Worker entry for TrafficWatch AI PWA
// Handles: precaching, runtime caching, push notifications, offline fallback

import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from "workbox-strategies";

// Clean up old precaches
cleanupOutdatedCaches();

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// ─── Runtime Caching ───────────────────────────────────

// Cache Google Fonts with Cache First strategy
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: "google-fonts-cache",
  })
);

// Cache Leaflet tile images with Cache First (long TTL)
registerRoute(
  /^https:\/\/[acst]\.tile\.openstreetmap\.org\/.*/i,
  new CacheFirst({
    cacheName: "map-tile-cache",
  })
);

// Cache API responses with Network First (fallback to cache)
registerRoute(
  /^https:\/\/.*\.supabase\.co\/.*/i,
  new NetworkFirst({
    cacheName: "api-cache",
    networkTimeoutSeconds: 5,
  })
);

// Cache static images with Cache First
registerRoute(
  /\.(?:png|jpg|jpeg|svg|gif|webp)$/,
  new CacheFirst({
    cacheName: "image-cache",
  })
);

// Cache JS and CSS with StaleWhileRevalidate
registerRoute(
  /\.(?:js|css)$/,
  new StaleWhileRevalidate({
    cacheName: "static-resources",
  })
);

// ─── Push Notification Event Handling ──────────────────

/**
 * Handle incoming push events from the server.
 * The server sends a JSON payload with title, body, icon, and data.
 */
self.addEventListener("push", (event) => {
  if (!(self.Notification && self.Notification.permission === "granted")) {
    return;
  }

  let data = {
    title: "TrafficWatch AI",
    body: "New notification",
    icon: "/icons/icon-192x192.png",
    badge: "/icons/icon-96x96.png",
    tag: `tw-${Date.now()}`,
    vibrate: [100],
    requireInteraction: false,
    silent: false,
    data: {
      url: "/dashboard",
      timestamp: new Date().toISOString(),
    },
  };

  try {
    if (event.data) {
      const payload = event.data.json();
      data = { ...data, ...payload };
    }
  } catch {
    // Plain text fallback
    if (event.data) {
      data.body = event.data.text();
    }
  }

  // Vibrate pattern based on urgency
  if (data.requireInteraction || data.data?.priority === "urgent") {
    data.vibrate = [200, 100, 200, 100, 200];
  }

  event.waitUntil(
    self.registration.showNotification(data.title, {
      body: data.body,
      icon: data.icon || "/icons/icon-192x192.png",
      badge: data.badge || "/icons/icon-96x96.png",
      tag: data.tag || `tw-${Date.now()}`,
      vibrate: data.vibrate,
      requireInteraction: data.requireInteraction ?? false,
      silent: data.silent ?? false,
      data: data.data || {},
      actions: [
        {
          action: "open",
          title: "Open",
        },
        {
          action: "dismiss",
          title: "Dismiss",
        },
      ],
    })
  );
});

/**
 * Handle notification click events.
 * - Clicking the notification body opens the app to the target URL.
 * - Clicking an action button performs the corresponding action.
 */
self.addEventListener("notificationclick", (event) => {
  event.notification.close();

  const urlToOpen = event.notification.data?.url || "/dashboard";

  if (event.action === "dismiss") {
    // Just close the notification
    return;
  }

  // Open or focus the app window
  event.waitUntil(
    clients.matchAll({ type: "window", includeUncontrolled: true }).then((windowClients) => {
      // Check if there's already a window open
      for (const client of windowClients) {
        if (client.url.includes(self.location.origin) && "focus" in client) {
          // Navigate to the target URL
          client.navigate(urlToOpen);
          return client.focus();
        }
      }
      // Open a new window
      if (clients.openWindow) {
        return clients.openWindow(urlToOpen);
      }
    })
  );
});

// ─── Offline Fallback ──────────────────────────────────

/**
 * Handle navigation requests — serve cached offline page when offline.
 */
self.addEventListener("fetch", (event) => {
  if (event.request.mode === "navigate") {
    event.respondWith(
      fetch(event.request).catch(() => {
        return caches.match("/offline-fallback.html").then((response) => {
          if (response) return response;
          // Last resort: return a minimal offline page
          return new Response(
            "<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Offline - TrafficWatch AI</title><style>body{font-family:sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;background:#0f172a;color:#e2e8f0;text-align:center;padding:20px}div{max-width:400px}.shield{font-size:48px;margin-bottom:16px}h1{font-size:20px;margin:0 0 8px}p{color:#94a3b8;font-size:14px;line-height:1.5}</style></head><body><div><div class='shield'>🛡️</div><h1>You're Offline</h1><p>TrafficWatch AI is unavailable offline. Please check your connection and try again.</p></div></body></html>",
            { headers: { "Content-Type": "text/html;charset=UTF-8" } }
          );
        });
      })
    );
  }
});

// ─── Service Worker Lifecycle ──────────────────────────

/**
 * Handle service worker updates — skip waiting and activate immediately.
 */
self.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") {
    self.skipWaiting();
  }

  // Handle notification data from client
  if (event.data?.type === "SHOW_NOTIFICATION") {
    const { title, options } = event.data;
    event.waitUntil(
      self.registration.showNotification(title, options)
    );
  }
});

/**
 * Clean up old caches on activation.
 */
self.addEventListener("activate", (event) => {
  const cacheWhitelist = [
    "google-fonts-cache",
    "map-tile-cache",
    "api-cache",
    "image-cache",
    "static-resources",
    "workbox-precaching-v2",
  ];

  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          if (!cacheWhitelist.includes(cacheName)) {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );

  // Claim all clients immediately
  event.waitUntil(clients.claim());
});
