// @ts-nocheck
// Service Worker entry for TrafficWatch AI PWA
// This file is processed by vite-plugin-pwa with injectManifest strategy

import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from "workbox-strategies";

// Clean up old precaches
cleanupOutdatedCaches();

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// Cache Google Fonts with Cache First strategy
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: "google-fonts-cache",
  })
);

// Cache Leaflet tile images with Cache First (long TTL)
registerRoute(
  /^https:\/\/[acst]\.tile\.openstreetmap\.org\/.*/i,
  new CacheFirst({
    cacheName: "map-tile-cache",
  })
);

// Cache API responses with Network First (fallback to cache)
registerRoute(
  /^https:\/\/.*\.supabase\.co\/.*/i,
  new NetworkFirst({
    cacheName: "api-cache",
    networkTimeoutSeconds: 5,
  })
);

// Cache static images with Cache First
registerRoute(
  /\.(?:png|jpg|jpeg|svg|gif|webp)$/,
  new CacheFirst({
    cacheName: "image-cache",
  })
);

// Cache JS and CSS with StaleWhileRevalidate
registerRoute(
  /\.(?:js|css)$/,
  new StaleWhileRevalidate({
    cacheName: "static-resources",
  })
);

// Handle offline fallback
self.addEventListener("fetch", (event) => {
  if (event.request.mode === "navigate") {
    event.respondWith(
      fetch(event.request).catch(() => {
        return caches.match("/offline.html");
      })
    );
  }
});

// Handle service worker updates
self.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});
