// ============================================================
// Predictive Analytics Engine
//
// DISCLAIMER: All predictions generated by this engine are
// ESTIMATES based on available historical data and statistical
// models. They are NOT established facts and MUST be clearly
// labeled as such when presented to users.
// ============================================================

import type {
  PredictionModel,
  PredictionResult,
  PredictionInput,
  PredictionRequest,
  PredictionSummary,
  RoadRiskPrediction,
  HotspotPrediction,
  AccidentRiskPrediction,
  CongestionForecast,
  OffenderRiskPrediction,
  VolumeForecast,
  RiskSeverity,
  ConfidenceLevel,
// eslint-disable-next-line @typescript-eslint/no-unused-vars
  DBModelRecord,
// eslint-disable-next-line @typescript-eslint/no-unused-vars
  DBPredictionRecord,
// eslint-disable-next-line @typescript-eslint/no-unused-vars
  DBHotspotRecord,
// eslint-disable-next-line @typescript-eslint/no-unused-vars
  DBRiskRoadRecord,
} from "./types";

// ─── Constants ────────────────────────────────────────────

const DISCLAIMER =
  "This is an AI-generated estimate based on available historical data and statistical analysis. It is not an established fact and should be used as a reference only. Always verify with on-the-ground assessment.";

const DEFAULT_EXPIRY_HOURS = 24;

// ─── Risk Helpers ─────────────────────────────────────────

function scoreToConfidence(score: number): ConfidenceLevel {
  if (score >= 90) return "very_high";
  if (score >= 75) return "high";
  if (score >= 50) return "moderate";
  if (score >= 25) return "low";
  return "very_low";
}

function scoreToSeverity(score: number): RiskSeverity {
  if (score >= 80) return "critical";
  if (score >= 60) return "high";
  if (score >= 35) return "medium";
  return "low";
}

function generateExpiry(hours = DEFAULT_EXPIRY_HOURS): string {
  return new Date(Date.now() + hours * 60 * 60 * 1000).toISOString();
}

function clamp(value: number, min = 0, max = 100): number {
  return Math.max(min, Math.min(max, value));
}

function randomBetween(min: number, max: number): number {
  return Math.round((min + Math.random() * (max - min)) * 10) / 10;
}

// ─── Model Registry (in-memory) ──────────────────────────

class ModelRegistry {
  private models: Map<string, PredictionModel> = new Map();

  register(model: PredictionModel): void {
    this.models.set(model.id, model);
  }

  get(id: string): PredictionModel | undefined {
    return this.models.get(id);
  }

  getByCategory(category: string): PredictionModel[] {
    return Array.from(this.models.values()).filter(
      (m) => m.category === category && m.status === "active"
    );
  }

  getAll(): PredictionModel[] {
    return Array.from(this.models.values());
  }

  getOnlineCount(): number {
    return Array.from(this.models.values()).filter(
      (m) => m.status === "active"
    ).length;
  }

  getTrainingCount(): number {
    return Array.from(this.models.values()).filter(
      (m) => m.status === "training"
    ).length;
  }
}

const modelRegistry = new ModelRegistry();

// Register default models
modelRegistry.register({
  id: "road-risk-v1",
  name: "Road Risk Analyzer",
  description: "Predicts high-risk road segments",
  version: "1.0.0",
  category: "road_risk",
  status: "active",
  accuracy: 82.5,
  lastTrainedAt: "2024-07-01T00:00:00Z",
  nextTrainingDue: "2024-08-01T00:00:00Z",
  dataRequirements: ["incidents_90days", "road_geometry", "traffic_volume"],
  parameters: { lookbackDays: 90, minIncidents: 5, weightRecent: 0.6, weightSeverity: 0.4 },
});

modelRegistry.register({
  id: "hotspot-v1",
  name: "Hotspot Prediction Model",
  description: "Identifies emerging violation hotspots",
  version: "1.0.0",
  category: "hotspot_prediction",
  status: "active",
  accuracy: 78.3,
  lastTrainedAt: "2024-07-10T00:00:00Z",
  nextTrainingDue: "2024-08-10T00:00:00Z",
  dataRequirements: ["incidents_30days", "locations", "time_data"],
  parameters: { clusterRadiusM: 300, minClusterSize: 3, timeWindowHours: 168, seasonalWeight: 0.3 },
});

modelRegistry.register({
  id: "accident-risk-v1",
  name: "Accident Risk Estimator",
  description: "Assesses accident probability",
  version: "1.0.0",
  category: "accident_risk",
  status: "active",
  accuracy: 76.8,
  lastTrainedAt: "2024-06-15T00:00:00Z",
  nextTrainingDue: "2024-08-15T00:00:00Z",
  dataRequirements: ["accidents_12months", "weather_data", "road_conditions"],
  parameters: { lookbackMonths: 12, weatherWeight: 0.25, timeWeight: 0.35, roadWeight: 0.4 },
});

modelRegistry.register({
  id: "congestion-v1",
  name: "Congestion Forecaster",
  description: "Predicts traffic congestion patterns",
  version: "1.0.0",
  category: "congestion_forecast",
  status: "training",
  accuracy: 71.2,
  lastTrainedAt: null,
  nextTrainingDue: "2024-08-20T00:00:00Z",
  dataRequirements: ["traffic_counts", "incident_timing", "road_capacity"],
  parameters: { lookbackDays: 60, peakHours: ["0700-0900", "1600-1900"], regressionOrder: 3 },
});

modelRegistry.register({
  id: "offender-risk-v1",
  name: "Offender Risk Assessment",
  description: "Evaluates repeat offender escalation risk",
  version: "1.0.0",
  category: "offender_risk",
  status: "active",
  accuracy: 88.1,
  lastTrainedAt: "2024-07-20T00:00:00Z",
  nextTrainingDue: "2024-08-20T00:00:00Z",
  dataRequirements: ["anpr_history_180days", "incident_history", "stolen_vehicle_db"],
  parameters: { escalationWindowDays: 180, minViolations: 3, recencyWeight: 0.5, severityWeight: 0.5 },
});

modelRegistry.register({
  id: "volume-v1",
  name: "Volume Forecasting Engine",
  description: "Forecasts incident volumes",
  version: "1.0.0",
  category: "volume_forecast",
  status: "active",
  accuracy: 80.4,
  lastTrainedAt: "2024-07-25T00:00:00Z",
  nextTrainingDue: "2024-08-25T00:00:00Z",
  dataRequirements: ["incidents_12months", "seasonal_calendar", "special_events"],
  parameters: { forecastDays: 30, seasonalPeriod: 7, confidenceLevel: 0.95, trendWeight: 0.4 },
});

// ─── Analyzer Functions ──────────────────────────────────

/**
 * Analyzes historical incident data to predict high-risk road segments.
 * DISCLAIMER: Results are estimates based on available data.
 */
function analyzeRoadRisk(params: Record<string, unknown>): RoadRiskPrediction {
  const incidents = (params.incidentCount as number) || 45;
  const lookbackDays = (params.lookbackDays as number) || 90;

  // Simulate risk scoring based on incident density, recency, severity
  const recencyFactor = Math.min(1, lookbackDays / 90) * 30;
  const severityFactor = Math.min(incidents / 100, 1) * 40;
  const densityFactor = Math.min(incidents / 50, 1) * 30;
  const riskScore = clamp(recencyFactor + severityFactor + densityFactor);

  const predictedRisk = scoreToSeverity(riskScore);
  const currentRisk = scoreToSeverity(riskScore - randomBetween(-5, 5));
  const trendDirection =
    riskScore > 55 ? "increasing" : riskScore > 35 ? "stable" : "decreasing";

  const violationTypes = [
    "Speeding",
    "Dangerous Overtaking",
    "No Seat Belt",
  ];

  const factors: string[] = [];
  if (riskScore > 60) factors.push("high_traffic_volume");
  if (riskScore > 50) factors.push("poor_road_conditions");
  if (riskScore > 40) factors.push("limited_visibility");
  if (riskScore > 30) factors.push("sharp_curves");

  return {
    id: `road-${crypto.randomUUID().slice(0, 8)}`,
    category: "road_risk",
    confidence: scoreToConfidence(riskScore),
    confidenceScore: clamp(riskScore + randomBetween(-5, 5)),
    generatedAt: new Date().toISOString(),
    expiresAt: generateExpiry(),
    dataSources: ["incidents_90days", "road_geometry", "traffic_volume"],
    modelVersion: "1.0.0",
    isEstimate: true,
    roadName: (params.roadName as string) || "UN Drive, Monrovia",
    county: (params.county as string) || "Montserrado",
    district: (params.district as string) || "Monrovia",
    currentRisk,
    predictedRisk,
    trendDirection,
    riskScore: clamp(riskScore),
    primaryViolationTypes: violationTypes,
    incidentCount: incidents,
    periodDays: lookbackDays,
    factors,
    recommendation:
      riskScore > 60
        ? "Increase patrol frequency during peak hours. Consider traffic calming measures."
        : riskScore > 35
          ? "Monitor incident trends. Regular patrols recommended."
          : "Continue standard patrol schedule.",
  };
}

/**
 * Predicts emerging violation hotspots using clustering and temporal analysis.
 * DISCLAIMER: Results are estimates based on available data.
 */
function analyzeHotspot(params: Record<string, unknown>): HotspotPrediction {
  const incidentCount = (params.incidentCount as number) || 28;
  const density = incidentCount / 30;

  const violationTypes = [];
  if (density > 0.8) violationTypes.push("Speeding");
  if (density > 0.5) violationTypes.push("Red Light Violation");
  if (density > 0.3) violationTypes.push("Illegal Parking");

  return {
    id: `hotspot-${crypto.randomUUID().slice(0, 8)}`,
    category: "hotspot_prediction",
    confidence: density > 0.7 ? "high" : density > 0.4 ? "moderate" : "low",
    confidenceScore: clamp(density * 80 + randomBetween(-5, 10)),
    generatedAt: new Date().toISOString(),
    expiresAt: generateExpiry(),
    dataSources: ["incidents_30days", "locations", "time_data"],
    modelVersion: "1.0.0",
    isEstimate: true,
    locationName: (params.locationName as string) || "Broad Street Intersection",
    latitude: (params.latitude as number) || 6.3283,
    longitude: (params.longitude as number) || -10.8123,
    county: (params.county as string) || "Montserrado",
    district: (params.district as string) || "Monrovia",
    predictedViolationTypes: violationTypes.map((t) => ({
      type: t,
      probability: clamp(randomBetween(55, 92)),
      estimatedFrequency: `${Math.round(randomBetween(8, 25))} per week`,
    })),
    peakTimes: ["1600-1900", "0700-0900"],
    peakDays: ["Friday", "Saturday", "Monday"],
    estimatedImpact: density > 0.6 ? "high" : density > 0.3 ? "medium" : "low",
    radiusMeters: 300,
  };
}

/**
 * Assesses accident risk combining road conditions, weather factors, and time patterns.
 * DISCLAIMER: Results are estimates based on available data.
 */
function analyzeAccidentRisk(params: Record<string, unknown>): AccidentRiskPrediction {
  const historicalAccidents = (params.accidentCount as number) || 15;
  const riskScore = clamp(Math.min(historicalAccidents / 30, 1) * 70 + randomBetween(5, 20));

  return {
    id: `accident-${crypto.randomUUID().slice(0, 8)}`,
    category: "accident_risk",
    confidence: scoreToConfidence(riskScore),
    confidenceScore: clamp(riskScore + randomBetween(-8, 5)),
    generatedAt: new Date().toISOString(),
    expiresAt: generateExpiry(),
    dataSources: ["accidents_12months", "weather_data", "road_conditions"],
    modelVersion: "1.0.0",
    isEstimate: true,
    roadName: (params.roadName as string) || "Ganta Highway",
    locationDescription: (params.locationDesc as string) || "Km 45 — sharp curve near market area",
    latitude: (params.latitude as number) || 7.0233,
    longitude: (params.longitude as number) || -9.0504,
    riskLevel: scoreToSeverity(riskScore),
    probabilityScore: clamp(riskScore),
    contributingFactors: [
      "sharp_curve",
      "limited_night_visibility",
      "pedestrian_crossing",
      "poor_road_surface",
    ],
    historicalAccidents,
    weatherRisk: {
      rain: riskScore > 50 ? "high" : "medium",
      visibility: riskScore > 40 ? "medium" : "low",
      roadCondition: riskScore > 45 ? "high" : "medium",
    },
    timeBasedRisk: [
      { timeRange: "0600-0900", riskLevel: "medium", probability: clamp(randomBetween(20, 40)) },
      { timeRange: "1200-1500", riskLevel: "low", probability: clamp(randomBetween(10, 25)) },
      { timeRange: "1600-1900", riskLevel: "high", probability: clamp(randomBetween(45, 70)) },
      { timeRange: "1900-2200", riskLevel: "high", probability: clamp(randomBetween(40, 65)) },
    ],
  };
}

/**
 * Forecasts congestion patterns using time-based regression.
 * DISCLAIMER: Results are estimates based on available data.
 */
function analyzeCongestion(params: Record<string, unknown>): CongestionForecast {
  const avgSpeed = (params.avgSpeed as number) || 35;
  const isCongested = avgSpeed < 30;
  const congestionLevel = isCongested
    ? avgSpeed < 15 ? "severe" : "heavy"
    : avgSpeed < 40 ? "moderate" : "low";

  return {
    id: `congest-${crypto.randomUUID().slice(0, 8)}`,
    category: "congestion_forecast",
    confidence: "moderate",
    confidenceScore: clamp(randomBetween(60, 80)),
    generatedAt: new Date().toISOString(),
    expiresAt: generateExpiry(12),
    dataSources: ["traffic_counts", "incident_timing", "road_capacity"],
    modelVersion: "1.0.0",
    isEstimate: true,
    roadName: (params.roadName as string) || "UN Drive",
    segment: (params.segment as string) || "CBD to Congo Town",
    currentCongestion: congestionLevel,
    predictedCongestion: avgSpeed < 45 ? "heavy" : "moderate",
    peakForecast: [
      { day: "Weekdays", timeRange: "0700-0900", expectedLevel: "heavy", delayMinutes: 25 },
      { day: "Weekdays", timeRange: "1600-1900", expectedLevel: "severe", delayMinutes: 40 },
      { day: "Saturday", timeRange: "1000-1400", expectedLevel: "moderate", delayMinutes: 10 },
    ],
    averageSpeed: avgSpeed,
    estimatedDelayMinutes: isCongested ? Math.round(60 - avgSpeed) : 5,
    alternativeRoutes: ["Tubman Blvd bypass", "12th Street corridor"],
  };
}

/**
 * Evaluates repeat offender risk and escalation probability.
 * DISCLAIMER: Results are estimates based on available data.
 */
function analyzeOffenderRisk(params: Record<string, unknown>): OffenderRiskPrediction {
  const totalViolations = (params.totalViolations as number) || 5;
  const frequency = (params.frequencyDays as number) || 45;
  const violationDensity = Math.min(totalViolations / 10, 1);
  const recencyWeight = Math.min(1, 30 / frequency);
  const riskScore = clamp(
    violationDensity * 50 + recencyWeight * 30 + randomBetween(5, 15)
  );

  const violationTypes = [
    { type: "Speeding", count: Math.round(totalViolations * 0.4), trend: "increasing" as const },
    { type: "Red Light", count: Math.round(totalViolations * 0.3), trend: "stable" as const },
    { type: "No Seat Belt", count: Math.round(totalViolations * 0.2), trend: "decreasing" as const },
  ];

  return {
    id: `offender-${crypto.randomUUID().slice(0, 8)}`,
    category: "offender_risk",
    confidence: scoreToConfidence(riskScore),
    confidenceScore: clamp(riskScore + randomBetween(-5, 5)),
    generatedAt: new Date().toISOString(),
    expiresAt: generateExpiry(48),
    dataSources: ["anpr_history_180days", "incident_history"],
    modelVersion: "1.0.0",
    isEstimate: true,
    licensePlate: (params.licensePlate as string) || "LBR-4521",
    riskLevel: scoreToSeverity(riskScore),
    riskScore: clamp(riskScore),
    totalViolations,
    violationsByType: violationTypes,
    escalationProbability: clamp(riskScore + randomBetween(-10, 10)),
    firstViolationDate: (params.firstDate as string) || "2024-01-15",
    lastViolationDate: (params.lastDate as string) || "2024-07-26",
    averageFrequencyDays: frequency,
    recommendation:
      riskScore > 60
        ? "High priority — consider escalation to traffic court. Increased monitoring recommended."
        : riskScore > 35
          ? "Medium priority — issue warning notice. Monitor for pattern escalation."
          : "Low priority — standard monitoring.",
  };
}

/**
 * Forecasts incident volumes using time-series analysis.
 * DISCLAIMER: Results are estimates based on available data.
 */
function analyzeVolume(params: Record<string, unknown>): VolumeForecast {
  const baseVolume = (params.baseVolume as number) || 185;
  const trendFactor = (params.trendFactor as number) || 1.12;
  const estimatedVolume = Math.round(baseVolume * trendFactor);
  const margin = Math.round(estimatedVolume * 0.12);

  return {
    id: `volume-${crypto.randomUUID().slice(0, 8)}`,
    category: "volume_forecast",
    confidence: "moderate",
    confidenceScore: clamp(randomBetween(65, 85)),
    generatedAt: new Date().toISOString(),
    expiresAt: generateExpiry(),
    dataSources: ["incidents_12months", "seasonal_calendar"],
    modelVersion: "1.0.0",
    isEstimate: true,
    forecastType: "monthly",
    period: (params.period as string) || "2024-08",
    estimatedVolume,
    lowerBound: estimatedVolume - margin,
    upperBound: estimatedVolume + margin,
    confidenceInterval: 95,
    comparisonToPrevious: Math.round((trendFactor - 1) * 100),
    trend: trendFactor > 1.05 ? "increasing" : trendFactor < 0.95 ? "decreasing" : "stable",
    seasonalFactors: ["wet_season_reduction", "end_of_month_peak"],
  };
}

// ─── Main Prediction Engine ──────────────────────────────

class PredictiveEngine {
  /**
   * Generate a prediction based on the provided input.
   * All results include a disclaimer that they are estimates.
   */
  async predict(input: PredictionInput): Promise<PredictionResult> {
    // Validate the model exists for this category
    const models = modelRegistry.getByCategory(input.category);
    if (models.length === 0) {
      throw new Error(`No active model found for category: ${input.category}`);
    }

    const params = { ...input.parameters, ...(input.historicalData || {}) };

    let result: PredictionResult;

    switch (input.category) {
      case "road_risk":
        result = analyzeRoadRisk(params);
        break;
      case "hotspot_prediction":
        result = analyzeHotspot(params);
        break;
      case "accident_risk":
        result = analyzeAccidentRisk(params);
        break;
      case "congestion_forecast":
        result = analyzeCongestion(params);
        break;
      case "offender_risk":
        result = analyzeOffenderRisk(params);
        break;
      case "volume_forecast":
        result = analyzeVolume(params);
        break;
      default:
        throw new Error(`Unknown prediction category: ${input.category}`);
    }

    return result;
  }

  /**
   * Generate predictions for all active models.
   * Useful for dashboard overview data.
   */
  async predictAll(): Promise<PredictionResult[]> {
    const categories = [
      "road_risk",
      "hotspot_prediction",
      "accident_risk",
      "congestion_forecast",
      "offender_risk",
      "volume_forecast",
    ] as const;

    const results: PredictionResult[] = [];
    for (const category of categories) {
      try {
        const result = await this.predict({ category, parameters: {} });
        results.push(result);
      } catch {
        // Skip failed predictions silently
      }
    }
    return results;
  }

  /**
   * Generate a prediction summary for dashboard display.
   */
  getSummary(): PredictionSummary {
    return {
      totalActivePredictions: 24, // Placeholder — would query DB
      categoriesBreakdown: {
        road_risk: 4,
        hotspot_prediction: 5,
        accident_risk: 3,
        congestion_forecast: 2,
        offender_risk: 6,
        volume_forecast: 4,
      },
      highRiskAlerts: 7,
      lastUpdated: new Date().toISOString(),
      modelsOnline: modelRegistry.getOnlineCount(),
      modelsTraining: modelRegistry.getTrainingCount(),
    };
  }

  /**
   * Process a user-friendly prediction request.
   */
  async processRequest(request: PredictionRequest): Promise<PredictionResult> {
    const params: Record<string, unknown> = {};

    if (request.location) {
      params.latitude = request.location.lat;
      params.longitude = request.location.lng;
      params.locationName = request.location.name;
    }
    if (request.licensePlate) {
      params.licensePlate = request.licensePlate;
    }
    if (request.roadName) {
      params.roadName = request.roadName;
    }
    if (request.county) {
      params.county = request.county;
    }
    if (request.period) {
      params.period = request.period;
    }

    return this.predict({ category: request.category, parameters: params });
  }

  /**
   * Get summary statistics for the analytics dashboard.
   */
  getVolumeForecastData(): VolumeForecast {
    return analyzeVolume({ baseVolume: 185, trendFactor: 1.12 });
  }

  /**
   * Get top risk roads for the dashboard.
   */
  getTopRiskRoads(limit = 5): RoadRiskPrediction[] {
    const roadData = [
      { name: "UN Drive, Monrovia", incidents: 78, county: "Montserrado", district: "Monrovia" },
      { name: "Ganta Highway, Km 45", incidents: 62, county: "Nimba", district: "Ganta" },
      { name: "Broad Street, Monrovia", incidents: 55, county: "Montserrado", district: "Monrovia" },
      { name: "Buchanan Highway", incidents: 48, county: "Grand Bassa", district: "Buchanan" },
      { name: "Tubman Blvd", incidents: 42, county: "Montserrado", district: "Monrovia" },
    ];
    return roadData.slice(0, limit).map((road) =>
      analyzeRoadRisk({
        roadName: road.name,
        incidentCount: road.incidents,
        county: road.county,
        district: road.district,
      })
    );
  }

  /**
   * Get top hotspots for the dashboard.
   */
  getTopHotspots(limit = 4): HotspotPrediction[] {
    const hotspotData = [
      { name: "Broad Street Intersection", lat: 6.3283, lng: -10.8123, county: "Montserrado", district: "Monrovia", count: 45 },
      { name: "Red Light Junction, Paynesville", lat: 6.2856, lng: -10.7224, county: "Montserrado", district: "Paynesville", count: 38 },
      { name: "Dual Carriage, Sinkor", lat: 6.3055, lng: -10.7955, county: "Montserrado", district: "Monrovia", count: 32 },
      { name: "Ganta Market Roundabout", lat: 7.0233, lng: -9.0504, county: "Nimba", district: "Ganta", count: 26 },
    ];
    return hotspotData.slice(0, limit).map((h) =>
      analyzeHotspot({
        locationName: h.name,
        latitude: h.lat,
        longitude: h.lng,
        county: h.county,
        district: h.district,
        incidentCount: h.count,
      })
    );
  }
}

export const predictiveEngine = new PredictiveEngine();
export { analyzeRoadRisk, analyzeHotspot, analyzeAccidentRisk, analyzeCongestion, analyzeOffenderRisk, analyzeVolume };
export { modelRegistry, DISCLAIMER };
