-- ============================================================
-- SEED FILE — DEMO DATA REMOVED
-- This file is intentionally empty.
-- Demo/seed data should not be auto-inserted into production.
-- To add test data, run manual SQL inserts.
-- ============================================================
